P_draft <- data.frame(Js = numeric(length = 0), 
                      Year = factor(NULL), 
                      Rain_day = integer(length = 0), 
                      dry_days_pre = integer(length = 0), 
                      dry_days_post = integer(length = 0), 
                      Tree_ID = integer(length = 0), 
                      spp = factor(NULL), 
                      trt = factor(NULL), 
                      block = factor(NULL), 
                      PAR = numeric(length = 0), 
                      VPD = numeric(length = 0), 
                      VWC_deep_pre = numeric(length = 0), 
                      VWC_deep_post = numeric(length = 0), 
                      VWC_shallow_pre = numeric(length = 0), 
                      VWC_shallow_post = numeric(length = 0), 
                      temp = numeric(length = 0), 
                      previous_precip = numeric(length = 0))